#
# Chess symbols
#

# White
WHITE_KING = '♔'
WHITE_QUEEN = '♕'
WHITE_ROOK = '♖'
WHITE_BISHOP = '♗'
WHITE_KNIGHT = '♘'
WHITE_PAWN = '♙'
WHITE_PIECES = [WHITE_KING, WHITE_QUEEN, WHITE_ROOK, WHITE_BISHOP, WHITE_KNIGHT, WHITE_PAWN]

# Black
BLACK_KING = '♚'
BLACK_QUEEN = '♛'
BLACK_ROOK = '♜'
BLACK_BISHOP = '♝'
BLACK_KNIGHT = '♞'
BLACK_PAWN = '♟'
BLACK_PIECES = [BLACK_KING, BLACK_QUEEN, BLACK_ROOK, BLACK_BISHOP, BLACK_KNIGHT, BLACK_PAWN]

# Other
HIGHLIGHT = '█'

BACKEND_URL = 'http://127.0.0.1:8000'
